### ISSUE TITLE
stopSmsHandling function is not calling when I call startSmsHandling 

### ISSUE THREAD

**Issue by ReactNDev** [akvelon/react-native-sms-user-consent#15]
const message: SMSMessage =  startSmsHandling((event: { sms?: string }) => {
        console.log(event);
        var otp = retrieveVerificationCode(event?.sms,4)
        this.setState({ code: otp.toString() })
})

stopSmsHandling() should call automatically when we call startSmsHandling() function but it's not happing. NativeSmsListener is not stopping after allow or deny operation.

Please correct me I'm wrong ? I want to stop NativeSmsListener, how can I do that ?
Please try to reply as soon as you can.

**Comment by nilavanraj** [comment]
This works for me 
```
  useEffect(() => { 
   const stop = startSmsHandling( ( {sms}) => {
      console.log(sms)
      stop()
    })
  }, []);
```

**Comment by nilavanraj** [comment]
This works for me 
```
  useEffect(() => { 
   const stop = startSmsHandling( ( {sms}) => {
      console.log(sms)
      stop()
    })
  }, []);
```
