### ISSUE TITLE
[Error: Could not unsubscribe, broadcastReceiver is null]

### ISSUE THREAD

**Issue by moin-maniar** [akvelon/react-native-sms-user-consent#26]
When OTP is received like this: <#> Welcome to Apple.com. Your verification code is 1234.
In android I am facing this issue. Please help me with this issue:
**[Error: Could not unsubscribe, broadcastReceiver is null]**

**Comment by mrshakirov** [comment]
please check out your issue on the new published version 1.1.0, should be fixed (:
