### ISSUE TITLE
 Could not set unknown property 'classifier' for task ':eabdullazyanov_react-native-sms-user-consent:androidJavadocJar' of type org.gradle.api.tasks.bundling.Jar. * Try:

### ISSUE THREAD

**Issue by YuriLima23** [akvelon/react-native-sms-user-consent#28]
This error occurs when using gradle version 8 we need a PR to fix
![image](https://github.com/akvelon/react-native-sms-user-consent/assets/22965145/7aa9d0ab-d3d0-4f88-8016-1d91887468c4)

replacing the information on lines 106 and 111 with "archiveClassifier"

following this stackoverflow reference

[](https://stackoverflow.com/questions/75660848/could-not-set-unknown-property-classifier-for-task-idl-parsersourcejar-of)

**Comment by fhott-gringo** [comment]
same issue

**Comment by mrshakirov** [comment]
please check out your issue on the new published version 1.1.0, should be fixed (:
