### ISSUE TITLE
app crashing after installing the package

### ISSUE THREAD

**Issue by Saad9624** [akvelon/react-native-sms-user-consent#3]

**Comment by eabdullazyanov** [comment]
Hi @Saad9624,

Thank you for your feedback. Could you help us to investigate the issue by providing some info about the crash?

1) Your environment info - output of the `npx react-native info` command;
2) Device/Emulator model and OS version;
3) Is the crash happeninig if you install the package to an empty app created by `npx react-native init AwesomeProject`?
4) Also, minimal app on which the issue reproduces will help a lot.

Thanks.

**Comment by eabdullazyanov** [comment]
Closing this issue due to insufficient reproduction info and long time inactivity. Please, let us know if you manage to find some more details on this.
