### ISSUE TITLE
Crashes the app fully 

### ISSUE THREAD

**Issue by davewaldorf** [akvelon/react-native-sms-user-consent#37]
System:
    OS: macOS 13.6.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 34.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.4.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Watchman: 2024.01.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

    "expo": "^48.0.0",

when adding the package to my app it crashes the whole app even if I don't use the package in my application. what could be the issue? I get the same errors over and over again until I delete the package fully from my project.

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
ERROR TypeError: Cannot read property 'useContext of null, js engine: hermes ERROR Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and AppRegistry. registerComponent wasn't called., js engine: hermes
```

**Comment by DmitriiPetukhov** [comment]
Hello! I'm sorry to hear that you're experiencing issues.

Unfortunately, I wasn't able to reproduce the crash. Could you please provide the steps to reproduce the issue or a minimal example? This could be a list of steps on how to create a new project and replicate the problem there, or a small project that demonstrates the issue.
