### ISSUE TITLE
I when send token, with letters, exemple A,B,C . he return erro 

### ISSUE THREAD

**Issue by Luska066** [akvelon/react-native-sms-user-consent#39]
Exemple code : 738FP2
returns No code retrieved!

**Comment by Luska066** [comment]
Resolução : Dentro do arquivo retrievedVerificationCode

mude isso

 const codeRegExp = /\b[A-Za-z0-9]{6}\b/;
  const code = sms.match(codeRegExp)?.[0];
  return code ?? null;
  
  para isso
  
  const codeRegExp = /\b[A-Za-z0-9]{6}\b/;
  const code = sms.match(codeRegExp)?.[0];
  return code ?? null;

**Comment by DmitriiPetukhov** [comment]
Hello!

We just released version `1.2.0`, which includes a new API that enables the use of custom regular expression patterns. For example, you can retrieve codes in the following way:
```typescript
const retrievedCode = useSmsUserConsent('[A-Za-z0-9]{6}');
```
