### ISSUE TITLE
java.lang.IllegalArgumentException - Receiver not registered: com.akvelon.reactnativesmsuserconsent

### ISSUE THREAD

**Issue by Tahira-SCT** [akvelon/react-native-sms-user-consent#40]
Getting this crash on Android 14

Fatal Exception: java.lang.RuntimeException
Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 in com.akvelon.reactnativesmsuserconsent.d@fa42fab

**Comment by DmitriiPetukhov** [comment]
Hello! 

Could you please provide more details about the versions of the packages used in your project? If possible, please provide the full list of `dependencies` and `devDependencies` from your `package.json` file.

I tested the library on Android 14 using React Native 0.74.0 and did not encounter this exception. It's possible that there is a conflict with another library.
