### ISSUE TITLE
Google Play will reject my app for  Intent Redirection Vulnerability

### ISSUE THREAD

**Issue by LightKnight3r** [akvelon/react-native-sms-user-consent#5]
I got a notification from google like that: 
<img width="448" alt="Screen Shot 2021-08-06 at 11 34 33 AM" src="https://user-images.githubusercontent.com/20377958/128456598-765d60b1-f06f-45f2-a7ae-95aef81b2ceb.png">
and support link from google: https://support.google.com/faqs/answer/9267555
From this link, i saw a note:
<img width="789" alt="Screen Shot 2021-08-06 at 11 37 42 AM" src="https://user-images.githubusercontent.com/20377958/128456692-c7baed1d-49be-4ef7-9387-4993eb2d263b.png">
I think my issue was caused by this packages. Please help!

**Comment by BaderSerhan** [comment]
I am getting the same issue after using this package.
@LightKnight3r did you manage to fix it?

**Comment by LightKnight3r** [comment]
@BaderSerhan
I dont know but following this Google's guide https://developers.google.com/identity/sms-retriever/user-consent/request#2_start_listening_for_incoming_messages , i created new commit to fix this in my fork repo.

**Comment by LightKnight3r** [comment]
https://github.com/LightKnight3r/react-native-sms-user-consent/commit/f0444918c104d4f2a259b6411f8ed79c268e64bb

**Comment by BaderSerhan** [comment]
That's great, I'll try it out, thank you!
If you want you can create a pull request to this library from your fork and this way you'd contribute a fix to the library.
I'm sure @eabdullazyanov would be thankful.

**Comment by eabdullazyanov** [comment]
Hi @LightKnight3r,

Thank you for posting the issue and for the PR! I merged it and made a release so that the latest version of the package (1.0.10) that includes the fix, can be used.
