### ISSUE TITLE
Update to Android 10+

### ISSUE THREAD

**Issue by luizsn00** [akvelon/react-native-sms-user-consent#7]
Gradle sync failed: No variants found for ':eabdullazyanov_react-native-sms-user-consent'. Check build files to ensure at least one variant exists. at:
				com.android.tools.idea.gradle.project.sync.idea.svs.AndroidModule.deliverModels(AndroidModule.kt:191)
				com.android.tools.idea.gradle.project.sync.idea.svs.AndroidExtraModelProvider$Worker.populateBuildModels(AndroidExtraModelProvider.kt:121)
				com.android.tools.idea.gradle.project.sync.idea.svs.AndroidExtraModelProvider.populateBuildModels(AndroidExtraModelProvider.kt:81)
				org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:247)
				org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:117)
				org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
				org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:77)

**Comment by vadimkorr** [comment]
Hi @luizsn00 ,
Please verify that the SDK platform package for Android 10.0 API level 29 is checked in Tools -> SDK Manager. If not, check it and apply changes. Accept the license terms, install the package and then File -> Sync Project with Gradle Files (or open the project again)

Is this error occurred in the example app? How did you launch it?

**Comment by eabdullazyanov** [comment]
Hi @luizsn00, is the issue still relevant?
